# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright 2025 Ahmad Ali Parr / SnapKitty � https://github.com/SNAPKITTYWEST/phaser-ags
## ═══════════════════════════════════════════════════════════════════
##  PHASER AGS — OMAP3530 register map generated by Nim AST macros
##
##  Every register block, offset, and bit field is defined once here.
##  The macro system generates type-safe read/write/set/clear/toggle
##  procs at compile time — no runtime overhead, no magic numbers.
##
##  Matches: firmware/common/platform.h addresses
##           firmware/hal/*.c register offsets and bit definitions
## ═══════════════════════════════════════════════════════════════════

import ./macros

# ─── UART0 — NS16550A at 0x4806A000 ──────────────────────────────

defRegBlock Uart0, 0x4806A000:
  defReg thr, 0x00, u32, wo    # Transmit Holding Register
  defReg rbr, 0x00, u32, ro    # Receive Buffer Register
  defReg ier, 0x04, u32, rw:
    defField rxBreak, 4, 1     # Break condition interrupt
    defField rxData,  0, 1     # RX data ready interrupt
  defReg iir, 0x08, u32, ro    # Interrupt Identification
  defReg fcr, 0x08, u32, wo:
    defField dmaMode,   3, 1
    defField txFifoTrig, 6, 2
    defField rxFifoTrig, 4, 2
    defField fifoEnable, 0, 1
  defReg lcr, 0x0C, u32, rw:
    defField dllMode,  7, 1    # DLAB: divisor latch access
    defField breakCtl, 6, 1
    defField parity,   3, 3    # 000=none, 011=odd, 111=even
    defField stopBits, 2, 1
    defField wordLen,  0, 2    # 00=5, 01=6, 10=7, 11=8
  defReg mcr, 0x10, u32, rw:
    defField loopback, 4, 1
    defField out2, 3, 1
    defField out1, 2, 1
    defField rts, 1, 1
    defField dtr, 0, 1
  defReg lsr, 0x14, u32, ro:
    defField txEmpty,  6, 1    # THR empty
    defField txReady,  5, 1    # Transmitter holding register empty
    defField breakRcv, 4, 1
    defField framing,  3, 1
    defField parityErr,2, 1
    defField overrun,  1, 1
    defField rxReady,  0, 1    # Data ready
  defReg mdr1, 0x20, u32, rw:
    defField mode, 0, 3       # 0=16x, 7=disable

# ─── GPIO1 — at 0x48310000 ───────────────────────────────────────

defRegBlock Gpio1, 0x48310000:
  defReg revision,   0x000, u32, ro
  defReg sysconfig,  0x010, u32, rw:
    defField autoIdle, 0, 1
    defField softReset, 1, 1
  defReg sysstatus,  0x014, u32, ro:
    defField resetDone, 0, 1
  defReg irqStatus1, 0x018, u32, rw:
    defField line0, 0, 1
  defReg irqEnable1, 0x01C, u32, rw:
    defField irq0, 0, 1
  defReg ctrl,       0x030, u32, rw:
    defField gatingCtrl, 0, 1
  defReg oe,         0x034, u32, rw    # Output enable (1=input, 0=output)
  defReg dataIn,     0x038, u32, ro
  defReg dataOut,    0x03C, u32, rw
  defReg setDataOut, 0x040, u32, wo
  defReg clearDataOut,0x044, u32, wo
  defReg risingDetect,  0x048, u32, rw
  defReg fallingDetect, 0x04C, u32, rw
  defReg debounceEn,    0x050, u32, rw
  defReg debounceTime,  0x054, u32, rw

# ─── AINTC — at 0x48200000 ───────────────────────────────────────

defRegBlock Aintc, 0x48200000:
  defReg revision,  0x000, u32, ro
  defReg sysconfig, 0x010, u32, rw:
    defField autoIdle, 0, 1
    defField softReset, 1, 1
  defReg sirIrq,    0x040, u32, ro:
    defField activeIrq, 0, 7   # Active IRQ number
  defReg sirFiq,    0x044, u32, ro:
    defField activeFiq, 0, 7
  defReg control,   0x048, u32, wo:
    defField newIrq, 0, 1      # Write 1 for IRQ end
    defField newFiq, 1, 1
  defReg mir0,      0x084, u32, rw   # Mask IRQ 0-31
  defReg mir1,      0x0A4, u32, rw   # Mask IRQ 32-63
  defReg mir2,      0x0C4, u32, rw   # Mask IRQ 64-95
  defReg mirClear0, 0x0B4, u32, wo
  defReg mirClear1, 0x0D4, u32, wo
  defReg mirClear2, 0x0F4, u32, wo
  defReg mirSet0,   0x08C, u32, wo
  defReg mirSet1,   0x0AC, u32, wo
  defReg mirSet2,   0x0CC, u32, wo

# ─── SDRC — at 0x6D000000 ───────────────────────────────────────

defRegBlock Sdrc, 0x6D000000:
  defReg sysconfig,  0x010, u32, rw
  defReg status,     0x014, u32, ro
  defReg csCfg,      0x040, u32, rw
  defReg sharing,    0x044, u32, rw
  defReg mcfg0,      0x080, u32, rw:    # CS0 SDRAM config
    defField casLatency, 4, 3
    defField sdramType,  12, 2
    defField cl3,        19, 1
  defReg mr0,        0x084, u32, rw:    # CS0 Mode Register
    defField casLat, 4, 3
    defField burstLen, 0, 3
  defReg emr0,       0x088, u32, rw
  defReg actim0Cs0,  0x09C, u32, rw:
    defField tRd2Rd,  0, 2
    defField tRd2Wr,  2, 2
    defField tRd2Pch, 4, 2
    defField tWr2Rd,  8, 2
    defField tRAS,    12, 4
    defField tRC,     16, 4
    defField tRCD,    20, 3
    defField tRP,     24, 3
  defReg rfrCtrl0,   0x0A4, u32, rw:
    defField refreshRate, 0, 13
    defField enableRefresh, 31, 1
  defReg power0,     0x0B0, u32, rw

# ─── GPMC — at 0x6E000000 ───────────────────────────────────────

defRegBlock Gpmc, 0x6E000000:
  defReg sysconfig,  0x010, u32, rw
  defReg irqStatus,  0x018, u32, rw
  defReg irqEnable,  0x01C, u32, rw
  defReg timeoutCtrl,0x040, u32, rw
  defReg config1_0,  0x060, u32, rw:   # CS0 NOR Flash
    defField devType,   12, 2   # 00=NOR, 01=NAND
    defField muxAddData, 8, 2   # 0=non-muxed
    defField devSize,    14, 2   # 00=8bit, 01=16bit
    defField readType,   0,  1   # 0=async
    defField writeType,  5,  1
  defReg config2_0,  0x064, u32, rw:   # CS0 timing
    defField csOnTime,   0,  4
    defField csRdOffTime, 8,  4
    defField csWrOffTime, 16, 4
  defReg config3_0,  0x068, u32, rw:
    defField advOnTime,   0,  4
    defField advRdOffTime, 8,  4
    defField advWrOffTime, 16, 4
  defReg config4_0,  0x06C, u32, rw:
    defField oeOnTime,  0,  4
    defField oeOffTime, 8,  4
    defField weOnTime,  16, 4
    defField weOffTime, 24, 4
  defReg config5_0,  0x070, u32, rw:
    defField rdCycleTime,  0, 4
    defField wrCycleTime,  8, 4
    defField rdAccessTime, 16, 4
  defReg config6_0,  0x074, u32, rw:
    defField wrDataOnBus,  0, 4
    defField cycle2Cycle,  8, 4
  defReg config7_0,  0x078, u32, rw:
    defField baseAddress,  0, 6
    defField csValid,      6, 1
    defField maskAddress,  8, 6

# ─── Clock Manager — at 0x48004000 ───────────────────────────────

defRegBlock ClockMgr, 0x48004000:
  defReg fclken1Core, 0x0500, u32, rw:
    defField uart1En, 0, 1
    defField uart2En, 1, 1
    defField i2c1En,  2, 1
    defField i2c2En,  3, 1
    defField mcspi1En, 4, 1
    defField mcspi2En, 5, 1
  defReg iclken1Core, 0x0510, u32, rw:
    defField uart1Iclk, 0, 1
    defField uart2Iclk, 1, 1
    defField i2c1Iclk,  2, 1
    defField i2c2Iclk,  3, 1
    defField mcspi1Iclk,4, 1
    defField mcspi2Iclk,5, 1
  defReg fclkenDss,   0x0D00, u32, rw
  defReg iclkenDss,   0x0D10, u32, rw
  defReg iclkenWkup,  0x0410, u32, rw:
    defField gpio1Iclk, 2, 1
  defReg clkenDpll1,  0x0D04, u32, rw:
    defField dpll1Mode, 0, 2
  defReg clkenDpll5,  0x0D44, u32, rw:
    defField dpll5Mode, 0, 2
